# Generated by Django 2.1.7 on 2019-05-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0005_mensagemdecontato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app_noticias.Tag'),
        ),
    ]
